Repository mamba-org/mamba, pull requests merged in 2023-04, with the labels that each got.

#2433 Use custom function to properly parse matchspec
  libmamba/include/mamba/core/match_spec.hpp
  libmamba/include/mamba/core/pool.hpp
  libmamba/include/mamba/core/solver.hpp
  libmamba/src/core/match_spec.cpp
  libmamba/src/core/pool.cpp
  libmamba/src/core/satisfiability_error.cpp
  libmamba/src/core/solver.cpp
  libmambapy/libmambapy/__init__.pyi
  libmambapy/src/main.cpp
  micromamba/src/update.cpp
Labels: type::general-improvement, where::libsolv, type::refactoring

#2417 Windows: Fixed environment variables not read as unicode.
  libmamba/include/mamba/core/environment.hpp
  libmamba/include/mamba/core/util_os.hpp
  libmamba/include/mamba/core/util_random.hpp
  libmamba/src/core/environment.cpp
  libmamba/src/core/util_os.cpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/src/core/test_system_env.cpp
  libmamba/tests/src/core/test_util_os.cpp
Labels: type::bug

#2428 Fix segfault in add_pin/all_problems_structured
  libmamba/include/mamba/core/match_spec.hpp
  libmamba/src/api/install.cpp
  libmamba/src/api/update.cpp
  libmamba/src/core/pool.cpp
  libmamba/src/core/solver.cpp
  micromamba/tests/test_create.py
Labels: type::bug, where::libsolv

#2421 Wrap more libcurl calls
  libmamba/include/mamba/core/url.hpp
  libmamba/include/mamba/core/util.hpp
  libmamba/src/core/curl.cpp
  libmamba/src/core/curl.hpp
  libmamba/src/core/fetch.cpp
  libmamba/src/core/url.cpp
  libmamba/src/core/util.cpp
Labels: type::general-improvement, type::refactoring

#2409 No Storing Channel* and MRepo* in Solvables
  libmamba/include/mamba/core/repo.hpp
  libmamba/include/mamba/core/transaction.hpp
  libmamba/src/api/channel_loader.cpp
  libmamba/src/api/repoquery.cpp
  libmamba/src/core/pool.cpp
  libmamba/src/core/prefix_data.cpp
  libmamba/src/core/repo.cpp
  libmamba/src/core/subdirdata.cpp
  libmamba/src/core/transaction.cpp
  libmamba/tests/src/core/test_env_file_reading.cpp
  micromamba/src/constructor.cpp
Labels: type::general-improvement, where::libsolv, type::refactoring

#2432 Context structuring
  libmamba/include/mamba/api/configuration.hpp
  libmamba/include/mamba/core/context.hpp
  libmamba/src/api/configuration.cpp
  libmamba/src/api/info.cpp
  libmamba/src/api/install.cpp
  libmamba/src/api/list.cpp
  libmamba/src/api/remove.cpp
  libmamba/src/api/repoquery.cpp
  libmamba/src/api/shell.cpp
  libmamba/src/api/update.cpp
  libmamba/src/core/context.cpp
  libmamba/src/core/curl.cpp
  libmamba/src/core/fetch.cpp
  libmamba/src/core/history.cpp
  libmamba/src/core/link.cpp
  libmamba/src/core/output.cpp
  libmamba/src/core/package_handling.cpp
  libmamba/src/core/pool.cpp
  libmamba/src/core/progress_bar_impl.cpp
  libmamba/src/core/query.cpp
  libmamba/src/core/run.cpp
  libmamba/src/core/shell_init.cpp
  libmamba/src/core/solver.cpp
  libmamba/src/core/subdirdata.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/core/util.cpp
  libmamba/src/core/util_os.cpp
  libmamba/tests/src/core/test_configuration.cpp
  libmamba/tests/src/core/test_cpp.cpp
  libmamba/tests/src/core/test_output.cpp
  libmamba/tests/src/core/test_satisfiability_error.cpp
  libmamba/tests/src/core/test_thread_utils.cpp
  libmamba/tests/src/core/test_transfer.cpp
  libmambapy/libmambapy/__init__.pyi
  libmambapy/src/main.cpp
  mamba/mamba/utils.py
  micromamba/src/env.cpp
  micromamba/src/main.cpp
  micromamba/src/umamba.cpp
Labels: type::general-improvement, type::refactoring

#2452 Clean up `fetch`
  libmamba/include/mamba/core/fetch.hpp
  libmamba/src/api/install.cpp
  libmamba/src/core/fetch.cpp
  libmamba/src/core/subdirdata.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/core/validate.cpp
  libmamba/tests/src/core/test_transfer.cpp
Labels: type::general-improvement, type::refactoring

#2467 Add topological sort
  libmamba/include/mamba/util/graph.hpp
  libmamba/src/core/query.cpp
  libmamba/tests/src/util/test_graph.cpp
Labels: type::general-improvement, type::refactoring

#2478 Store PackageInfo::track_features as a vector
  libmamba/include/mamba/core/package_info.hpp
  libmamba/src/core/package_info.cpp
  libmamba/src/core/pool.cpp
  libmamba/src/core/query.cpp
  libmambapy/libmambapy/__init__.pyi
  libmambapy/src/main.cpp
Labels: type::general-improvement, type::refactoring

#2472 Use topological sort instead of libsolv
  libmamba/src/core/prefix_data.cpp
Labels: type::general-improvement, type::refactoring

#2488 track_feature typo
  libmamba/src/core/package_info.cpp
Labels: type::bug

#2460 Resume `Context` structuring
  docs/source/python_api.rst
  libmamba/include/mamba/core/context.hpp
  libmamba/src/api/clean.cpp
  libmamba/src/api/configuration.cpp
  libmamba/src/api/create.cpp
  libmamba/src/api/info.cpp
  libmamba/src/api/install.cpp
  libmamba/src/api/list.cpp
  libmamba/src/api/remove.cpp
  libmamba/src/api/repoquery.cpp
  libmamba/src/api/shell.cpp
  libmamba/src/api/update.cpp
  libmamba/src/core/activation.cpp
  libmamba/src/core/channel.cpp
  libmamba/src/core/context.cpp
  libmamba/src/core/environments_manager.cpp
  libmamba/src/core/fetch.cpp
  libmamba/src/core/link.cpp
  libmamba/src/core/menuinst.cpp
  libmamba/src/core/run.cpp
  libmamba/src/core/shell_init.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/core/transaction_context.cpp
  libmamba/src/core/util.cpp
  libmamba/tests/src/core/test_cpp.cpp
  libmambapy/libmambapy/__init__.pyi
  libmambapy/src/main.cpp
  mamba/mamba/api.py
  mamba/mamba/mamba.py
  mamba/mamba/mamba_env.py
  mamba/mamba/utils.py
  micromamba/src/config.cpp
  micromamba/src/env.cpp
  micromamba/src/shell.cpp
  micromamba/src/update.cpp
Labels: type::general-improvement, type::refactoring

#2489 Move `repoquery` python test from libmamba (not run) to mamba
  mamba/tests/test_repoquery.py
Labels: type::cleanup

#2401 Wrap ::Pool and ::Repo
  libmamba/CMakeLists.txt
  libmamba/src/core/repo.cpp
  libmamba/src/solv-cpp/ids.hpp
  libmamba/src/solv-cpp/pool.cpp
  libmamba/src/solv-cpp/pool.hpp
  libmamba/src/solv-cpp/queue.cpp
  libmamba/src/solv-cpp/queue.hpp
  libmamba/src/solv-cpp/repo.cpp
  libmamba/src/solv-cpp/repo.hpp
  libmamba/src/solv-cpp/solvable.cpp
  libmamba/src/solv-cpp/solvable.hpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/src/solv-cpp/test_pool.cpp
  libmamba/tests/src/solv-cpp/test_queue.cpp
  libmamba/tests/src/solv-cpp/test_repo.cpp
  libmamba/tests/src/solv-cpp/test_solvable.cpp
Labels: type::general-improvement, where::libsolv, type::refactoring

#2468 Curl wrapping
  libmamba/include/mamba/core/fetch.hpp
  libmamba/src/core/curl.cpp
  libmamba/src/core/curl.hpp
  libmamba/src/core/fetch.cpp
Labels: type::general-improvement, type::refactoring
