Repository mamba-org/mamba, pull requests merged in 2023-06, with the labels that each got.

#2556 Fix stubgens
  libmambapy/libmambapy/__init__.pyi
Labels: type::bug, what::ci

#2560 Fix server auth test
  .github/workflows/main.yml
  mamba/environment-dev.yml
  mamba/tests/testserver.sh
Labels: type::bug, what::ci

#2554 Wrap libsolv Transaction
  libmamba/CMakeLists.txt
  libmamba/src/solv-cpp/ids.hpp
  libmamba/src/solv-cpp/queue.cpp
  libmamba/src/solv-cpp/queue.hpp
  libmamba/src/solv-cpp/solvable.cpp
  libmamba/src/solv-cpp/solvable.hpp
  libmamba/src/solv-cpp/solver.cpp
  libmamba/src/solv-cpp/solver.hpp
  libmamba/src/solv-cpp/transaction.cpp
  libmamba/src/solv-cpp/transaction.hpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/src/solv-cpp/pool_data.cpp
  libmamba/tests/src/solv-cpp/pool_data.hpp
  libmamba/tests/src/solv-cpp/test_queue.cpp
  libmamba/tests/src/solv-cpp/test_solver.cpp
  libmamba/tests/src/solv-cpp/test_transaction.cpp
Labels: type::general-improvement, where::libsolv, type::refactoring

#2564 Split the transaction.hpp header
  libmamba/CMakeLists.txt
  libmamba/include/mamba/core/package_download.hpp
  libmamba/include/mamba/core/transaction.hpp
  libmamba/src/api/configuration.cpp
  libmamba/src/api/install.cpp
  libmamba/src/core/package_download.cpp
  libmamba/src/core/transaction.cpp
Labels: type::general-improvement, type::refactoring, where::libmamba

#2565 use ObjTransaction in MTransaction
  libmamba/include/mamba/core/solver.hpp
  libmamba/include/mamba/core/transaction.hpp
  libmamba/src/core/transaction.cpp
  libmamba/src/solv-cpp/pool.cpp
  libmamba/src/solv-cpp/pool.hpp
  libmamba/src/solv-cpp/queue.hpp
  libmamba/src/solv-cpp/repo.cpp
  libmamba/src/solv-cpp/repo.hpp
  libmamba/src/solv-cpp/transaction.cpp
  libmamba/src/solv-cpp/transaction.hpp
  libmamba/tests/src/solv-cpp/test_pool.cpp
  libmamba/tests/src/solv-cpp/test_repo.cpp
Labels: type::general-improvement, where::libsolv, type::refactoring

#2602 Use ObjSolver wrapper in MSolver
  libmamba/src/core/pool.cpp
  libmamba/src/core/solver.cpp
  libmamba/src/solv-cpp/ids.hpp
  libmamba/src/solv-cpp/pool.hpp
  libmamba/src/solv-cpp/repo.hpp
  libmamba/tests/src/solv-cpp/test_pool.cpp
  libmamba/tests/src/solv-cpp/test_repo.cpp
Labels: where::libsolv, type::refactoring

#2537 Channels refactoring/cleaning
  libmamba/include/mamba/core/channel.hpp
  libmamba/include/mamba/core/url.hpp
  libmamba/include/mamba/core/util_os.hpp
  libmamba/src/core/channel.cpp
  libmamba/src/core/solver.cpp
  libmamba/src/core/subdirdata.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/core/url.cpp
  libmamba/src/core/util_os.cpp
  libmamba/tests/src/core/test_channel.cpp
  libmamba/tests/src/core/test_url.cpp
  libmamba/tests/src/core/test_util_os.cpp
  micromamba/src/env.cpp
  micromamba/tests/test_config.py
Labels: type::general-improvement, type::refactoring
