Repository mamba-org/mamba, pull requests merged in 2023-03, with the labels that each got.

#2303 Fix some warnings
  libmamba/include/mamba/core/context.hpp
  libmamba/include/mamba/core/satisfiability_error.hpp
  libmamba/src/core/context.cpp
  libmamba/src/core/menuinst.cpp
  libmamba/src/core/package_handling.cpp
  libmamba/src/core/prefix_data.cpp
  libmamba/src/core/run.cpp
  libmamba/src/core/satisfiability_error.cpp
  libmamba/src/core/shell_init.cpp
  libmamba/src/core/subdirdata.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/core/util.cpp
  micromamba/src/common_options.cpp
Labels: type::bug, type::general-improvement

#2289 Isolate solv::ObjQueue
  libmamba/CMakeLists.txt
  libmamba/include/mamba/api/install.hpp
  libmamba/include/mamba/core/package_info.hpp
  libmamba/include/mamba/core/query.hpp
  libmamba/include/mamba/core/repo.hpp
  libmamba/include/mamba/core/solver.hpp
  libmamba/include/mamba/core/transaction.hpp
  libmamba/include/mamba/solv-cpp/queue.hpp
  libmamba/src/core/package_info.cpp
  libmamba/src/core/pool.cpp
  libmamba/src/core/prefix_data.cpp
  libmamba/src/core/query.cpp
  libmamba/src/core/repo.cpp
  libmamba/src/core/solver.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/solv-cpp/queue.cpp
  libmamba/src/solv-cpp/queue.hpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/solv-cpp/test_queue.cpp
  micromamba/src/run.cpp
Labels: type::general-improvement, where::solver, type::refactoring

#2318 Improve Python conflicts
  libmamba/include/mamba/core/package_info.hpp
  libmamba/include/mamba/core/query.hpp
  libmamba/include/mamba/core/satisfiability_error.hpp
  libmamba/include/mamba/core/util_graph.hpp
  libmamba/src/core/query.cpp
  libmamba/src/core/satisfiability_error.cpp
  libmamba/src/core/solver.cpp
  libmamba/tests/test_satisfiability_error.cpp
  libmamba/tests/test_util_graph.cpp
  libmambapy/libmambapy/__init__.pyi
  libmambapy/src/main.cpp
Labels: type::general-improvement

#2340 Isolate PackageInfo from libsolv
  libmamba/include/mamba/core/package_info.hpp
  libmamba/include/mamba/core/pool.hpp
  libmamba/include/mamba/core/repo.hpp
  libmamba/include/mamba/core/solver.hpp
  libmamba/include/mamba/core/transaction.hpp
  libmamba/src/api/install.cpp
  libmamba/src/api/remove.cpp
  libmamba/src/api/update.cpp
  libmamba/src/core/package_info.cpp
  libmamba/src/core/pool.cpp
  libmamba/src/core/prefix_data.cpp
  libmamba/src/core/query.cpp
  libmamba/src/core/satisfiability_error.cpp
  libmamba/src/core/solver.cpp
  libmamba/src/core/transaction.cpp
  libmambapy/libmambapy/__init__.pyi
  libmambapy/src/main.cpp
  mamba/mamba/mamba.py
  mamba/mamba/mamba_env.py
Labels: type::general-improvement, type::refactoring

#2344 Add strip_if functions
  libmamba/include/mamba/core/util_string.hpp
  libmamba/src/core/util_string.cpp
  libmamba/tests/test_util_string.cpp
Labels: type::general-improvement

#2347 Add strip_parts functions
  libmamba/include/mamba/core/util_string.hpp
  libmamba/src/core/util_string.cpp
  libmamba/tests/test_util_string.cpp
Labels: type::general-improvement

#2376 First version/steps of unraveling `fetch` code and wrapping libcurl
  libmamba/include/mamba/core/fetch.hpp
  libmamba/src/core/curl.cpp
  libmamba/src/core/curl.hpp
  libmamba/src/core/fetch.cpp
Labels: type::general-improvement, backward incompatible, type::refactoring

#2391 Parse repodata.json
  libmamba/CMakeLists.txt
  libmamba/include/mamba/specs/repo_data.hpp
  libmamba/src/specs/repo_data.cpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/src/specs/test_repo_data.cpp
Labels: type::general-improvement, type::refactoring

#2416 Refactor test_create, test_proxy, and test_env for test isolation
  micromamba/setup.cfg
  micromamba/tests/conftest.py
  micromamba/tests/helpers.py
  micromamba/tests/test_create.py
  micromamba/tests/test_env.py
  micromamba/tests/test_proxy.py
  micromamba/tests/test_remove.py
  pyproject.toml
Labels: type::general-improvement, type::refactoring

#2423 Solve a corner case in the SAT error messages
  libmamba/src/core/satisfiability_error.cpp
Labels: type::bug
