Repository mamba-org/mamba, pull requests merged in 2024-07, with the labels that each got.

#3297 Fixed restoring the previous signal handler for example in python case (Windows only for now)
  libmamba/include/mamba/core/thread_utils.hpp
  libmamba/src/core/context.cpp
  libmamba/src/core/thread_utils.cpp
Labels: release::bug_fixes

#3321 Fix `test_no_python_pinning`
  micromamba/tests/test_install.py
Labels: release::bug_fixes

#3324 Attempt to fix `test_proxy_install`
  micromamba/tests/dump_proxy_connections.py
Labels: release::bug_fixes

#3357 doc(more_concepts.rst): improve clarity
  docs/source/advanced_usage/more_concepts.rst
Labels: release::ci_docs

#3358 Allow spaces in version after operator
  libmamba/src/specs/match_spec.cpp
  libmamba/src/specs/version_spec.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
Labels: release::bug_fixes

#3335 Remove logs for every package
  libmamba/src/solver/libsolv/helpers.cpp
Labels: release::enhancements

#3361 Allow leading lowercase letter in version
  libmamba/src/specs/version_spec.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
Labels: release::bug_fixes

#3355 Update mamba.xsh: support xonsh >= 0.18.0
  libmamba/data/mamba.xsh
Labels: release::enhancements

#3350 chore(ci): bump github action versions
  .github/actions/workspace/action.yml
  .github/workflows/label_check.yml
  .github/workflows/linters.yml
  .github/workflows/static_build.yml
Labels: release::ci_docs

#3363 Make more classes hashable and comparable
  libmamba/include/mamba/specs/build_number_spec.hpp
  libmamba/include/mamba/specs/chimera_string_spec.hpp
  libmamba/include/mamba/specs/glob_spec.hpp
  libmamba/include/mamba/specs/match_spec.hpp
  libmamba/include/mamba/specs/package_info.hpp
  libmamba/include/mamba/specs/regex_spec.hpp
  libmamba/include/mamba/specs/unresolved_channel.hpp
  libmamba/include/mamba/specs/version_spec.hpp
  libmamba/include/mamba/util/flat_binary_tree.hpp
  libmamba/include/mamba/util/flat_bool_expr_tree.hpp
  libmamba/include/mamba/util/flat_set.hpp
  libmamba/include/mamba/util/heap_optional.hpp
Labels: release::enhancements

#3368 build: Support fmt 11
  libmamba/include/mamba/download/mirror.hpp
  libmamba/include/mamba/fs/filesystem.hpp
  libmamba/include/mamba/specs/build_number_spec.hpp
  libmamba/include/mamba/specs/chimera_string_spec.hpp
  libmamba/include/mamba/specs/glob_spec.hpp
  libmamba/include/mamba/specs/match_spec.hpp
  libmamba/include/mamba/specs/regex_spec.hpp
  libmamba/include/mamba/specs/version.hpp
  libmamba/include/mamba/specs/version_spec.hpp
  libmamba/src/api/install.cpp
  libmamba/src/core/context.cpp
  libmamba/src/core/query.cpp
  libmamba/src/core/run.cpp
  libmamba/src/solver/libsolv/unsolvable.cpp
  libmamba/src/specs/build_number_spec.cpp
  libmamba/src/specs/chimera_string_spec.cpp
  libmamba/src/specs/glob_spec.cpp
  libmamba/src/specs/match_spec.cpp
  libmamba/src/specs/package_info.cpp
  libmamba/src/specs/regex_spec.cpp
  libmamba/src/specs/unresolved_channel.cpp
  libmamba/src/specs/version.cpp
  libmamba/src/specs/version_spec.cpp
  libmamba/src/util/os_win.cpp
  micromamba/src/run.cpp
Labels: release::enhancements

#3365 Restore previous behavior of `MAMBA_ROOT_PREFIX`
  libmamba/src/api/configuration.cpp
Labels: release::bug_fixes

#3369 test: Comparability and hashability of `PackageInfo` and `MatchSpec`
  libmamba/include/mamba/specs/match_spec.hpp
  libmamba/include/mamba/specs/regex_spec.hpp
  libmamba/include/mamba/util/flat_set.hpp
  libmamba/include/mamba/util/heap_optional.hpp
  libmamba/src/specs/match_spec.cpp
  libmamba/tests/src/specs/test_build_number_spec.cpp
  libmamba/tests/src/specs/test_chimera_string_spec.cpp
  libmamba/tests/src/specs/test_glob_spec.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmamba/tests/src/specs/test_package_info.cpp
  libmamba/tests/src/specs/test_regex_spec.cpp
  libmamba/tests/src/specs/test_unresolved_channel.cpp
  libmamba/tests/src/specs/test_version_spec.cpp
Labels: release::enhancements

#3377 test: Adapt test_explicit_export_topologically_sorted
  micromamba/tests/test_env.py
Labels: release::enhancements
