Repository mamba-org/mamba, pull requests merged in 2024-10, with the labels that each got.

#3491 Rollback to micromamba 1.5.10 in CI
  .github/workflows/unix_impl.yml
Labels: release::ci_docs

#3488 Fix `channel` and `base_url` in `list` cmd
  docs/source/developer_zone/changes-2.0.rst
  libmamba/src/api/list.cpp
  micromamba/tests/test_create.py
  micromamba/tests/test_list.py
Labels: release::bug_fixes

#3489 Win activate
  libmamba/data/activate.bat
  libmamba/data/mamba_hook.bat
  libmamba/src/core/activation.cpp
  libmamba/src/core/shell_init.cpp
Labels: release::bug_fixes

#3490 fix: Handle `MatchSpec` with brackets when parsing environments' history
  libmamba/src/core/history.cpp
  libmamba/tests/data/history/parse_metadata/conda-meta/history
  libmamba/tests/src/core/test_history.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3497 Upgraded CI to micromamba 2.0.2
  .github/workflows/static_build.yml
  .github/workflows/unix_impl.yml
  .github/workflows/windows_impl.yml
Labels: release::ci_docs

#3507 Fix warnings and co
  libmamba/src/specs/match_spec.cpp
Labels: release::bug_fixes

#3510 Replace `[System.IO.Path]::GetFileNameWithoutExtension` with `-replace`
  libmamba/data/Mamba.psm1
Labels: release::bug_fixes

#3512 fix: Ignore inline comment in environment specification
  libmamba/src/specs/match_spec.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
Labels: release::bug_fixes

#3513 Add recommendation if error with root prefix
  libmamba/src/api/configuration.cpp
Labels: release::bug_fixes

#3465 Backport #3436
  libmamba/CMakeLists.txt
  micromamba/CMakeLists.txt
  micromamba/tests/test_repoquery.py
Labels: 1.x

#3537 fix: Adapt `test_env_update_pypi_with_conda_forge`
  micromamba/tests/test_env.py
Labels: release::bug_fixes

#3525 fix: Handle space in `mamba` and `micromamba` executable absolute paths
  libmamba/data/mamba.bat
Labels: release::bug_fixes

#3519 Create empty base prefix with `env update`
  libmamba/src/api/update.cpp
  micromamba/tests/test_env.py
  micromamba/tests/test_install.py
Labels: release::bug_fixes

#3544 dev: Remove the use of Taskfile
  Taskfile.dist.yml
  docs/source/developer_zone/dev_environment.rst
Labels: release::ci_docs

#3548 maint: Unpin libcurl<8.10
  .github/workflows/static_build.yml
  dev/environment-dev.yml
  dev/environment-micromamba-static.yml
Labels: release::ci_docs

#3545 Correctly rename test to be run
  libmamba/include/mamba/specs/package_info.hpp
  libmamba/src/core/package_fetcher.cpp
  micromamba/tests/test_install.py
Labels: release::bug_fixes

#3556 [windows-vcpkg] Replace deprecated openssl with crypto feature with latest libarchive
  vcpkg.json
Labels: release::ci_docs

#3540 Fix relative path in local channel
  libmamba/src/specs/unresolved_channel.cpp
  libmamba/tests/src/specs/test_unresolved_channel.cpp
  micromamba/tests/test_install.py
Labels: release::bug_fixes

#3546 windows shell init files use executable name
  .gitignore
  libmamba/data/activate.bat
  libmamba/data/mamba.bat
  libmamba/data/mamba_hook.bat
  libmamba/src/core/shell_init.cpp
  libmamba/src/core/util_os.cpp
  libmamba/src/util/os_win.cpp
Labels: release::bug_fixes

#3562 fix: Export the environment prefix in specification
  micromamba/src/env.cpp
  micromamba/tests/test_env.py
Labels: release::bug_fixes

#3563 fix: Support `conda env export` `no-builds` flag
  micromamba/src/env.cpp
  micromamba/tests/test_env.py
Labels: release::bug_fixes

#3559 fix: JSON output for environment export
  micromamba/src/env.cpp
  micromamba/tests/test_env.py
Labels: release::bug_fixes

#3521 fix: Only register channels in the context once
  libmamba/CMakeLists.txt
  libmamba/src/api/install.cpp
  libmamba/src/api/update.cpp
  libmamba/src/api/utils.cpp
  libmamba/src/api/utils.hpp
Labels: release::bug_fixes

#3564 chore: some CMake cleanup
  CMakeLists.txt
  docs/source/developer_zone/dev_environment.rst
  docs/source/installation/micromamba-installation.rst
  libmamba/CMakeLists.txt
  libmambapy/CMakeLists.txt
Labels: release::enhancements

#3565 pip packages support with `list`
  libmamba/include/mamba/core/activation.hpp
  libmamba/include/mamba/core/prefix_data.hpp
  libmamba/include/mamba/specs/package_info.hpp
  libmamba/include/mamba/util/environment.hpp
  libmamba/src/api/install.cpp
  libmamba/src/api/list.cpp
  libmamba/src/api/utils.cpp
  libmamba/src/core/activation.cpp
  libmamba/src/core/prefix_data.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/specs/package_info.cpp
  libmamba/src/util/environment.cpp
  micromamba/tests/test_list.py
Labels: release::enhancements

#3568 Fix doc
  docs/source/usage/solver.rst
  docs/source/usage/specs.rst
Labels: release::ci_docs

#3572 Fix locking error
  libmamba/src/core/prefix_data.cpp
  libmamba/src/core/util.cpp
Labels: release::bug_fixes
