Repository mamba-org/mamba, pull requests merged in 2024-12, with the labels that each got.

#3641 Uncomment test
  micromamba/tests/test_create.py
Labels: release::ci_docs

#3348 docs: Mention differences with `conda`
  README.md
Labels: release::ci_docs

#3645 docs: Remove hint on Homebrew
  docs/source/installation/micromamba-installation.rst
Labels: release::ci_docs

#3649 Allow repoquery on non env prefix
  libmamba/src/api/repoquery.cpp
Labels: release::bug_fixes

#3650 fix: Reintroduce the `uninstall` command
  micromamba/src/umamba.cpp
  micromamba/tests/helpers.py
  micromamba/tests/test_remove.py
Labels: release::bug_fixes

#3656 docs: Remove installation non-recommendation
  docs/source/installation/mamba-installation.rst
Labels: release::ci_docs

#3657 fix: Handle environment with empty or absent `dependencies`
  libmamba/src/api/install.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3644 fix: Effectively apply dry-run on installation from PyPI
  libmamba/src/api/install.cpp
  micromamba/tests/test_install.py
Labels: release::bug_fixes

#3640 Handle `.tar.gz` in pkg url
  libmamba/include/mamba/specs/archive.hpp
  libmamba/include/mamba/specs/package_info.hpp
  libmamba/src/specs/package_info.cpp
  libmambapy/tests/test_specs.py
  micromamba/tests/test-env-pip-lock.yaml
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3639 `micromamba/mamba --version` displays pre-release version names + establishes pre-release versions name scheme
  libmamba/include/mamba/version.hpp
  libmamba/include/mamba/version.hpp.tmpl
  libmambapy/src/libmambapy/version.py
  libmambapy/src/libmambapy/version.py.tmpl
  micromamba/src/version.hpp
  micromamba/src/version.hpp.tmpl
  releaser.py
  update_changelog.py
  version_scheme.py
Labels: release::enhancements

#3615 maint: Restructure docs configuration file and improve docs pages
  docs/source/conf.py
  docs/source/user_guide/configuration.rst
  docs/source/user_guide/troubleshooting.rst
Labels: release::ci_docs

#3662 fix: Skip empty lines in environment spec files
  dev/environment-dev.yml
  libmamba/include/mamba/util/string.hpp
  libmamba/src/api/install.cpp
  libmamba/src/core/util.cpp
  libmamba/src/util/string.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3669 Fixed uninitialized variable in curl handler
  libmamba/src/download/curl.cpp
Labels: release::bug_fixes

#3670 fix: Activated environment name
  libmamba/src/core/activation.cpp
  libmamba/tests/src/core/test_activation.cpp
Labels: release::bug_fixes

#3672 docs: Adapt shell completion subsection
  docs/source/installation/micromamba-installation.rst
  docs/source/user_guide/concepts.rst
Labels: release::ci_docs

#3671 maint: Add pyupgrade pre-commit hook
  .pre-commit-config.yaml
  docs/source/tools/mermaid.py
  docs/source/tools/mermaid_inheritance.py
  libmambapy/src/libmambapy/version.py
  micromamba/test-server/reposerver.py
  micromamba/tests/conftest.py
  micromamba/tests/helpers.py
  micromamba/tests/test_activation.py
  micromamba/tests/test_env.py
  micromamba/tests/test_package.py
  micromamba/tests/test_proxy.py
  micromamba/tests/test_remove.py
  micromamba/tests/test_run.py
  releaser.py
  update_changelog.py
  version_scheme.py
Labels: release::ci_docs

#3673 fix: Wrap `MAMBA_EXE` around double quotes in run shell script
  libmamba/src/core/util.cpp
Labels: release::bug_fixes

#3667 maint: Cleanup CMake files and delete not compiled files
  libmamba/CMakeLists.txt
  libmamba/ext/solv-cpp/tests/CMakeLists.txt
  libmamba/include/mamba/core/mirror.hpp
  libmamba/src/core/mirror.cpp
  libmamba/tests/CMakeLists.txt
  micromamba/CMakeLists.txt
Labels: release::ci_docs

#3676 Fix compilation with -Werror=unused-result
  .pre-commit-config.yaml
  micromamba/src/constructor.cpp
Labels: release::bug_fixes

#3678 build: Remove another uninitialized variable in curl handler
  libmamba/src/download/curl.cpp
Labels: release::bug_fixes

#3679 test: Add two tests on MatchSpec's version comparison
  libmamba/tests/src/specs/test_match_spec.cpp
Labels: release::bug_fixes

#3674 fix: Clarify shell init dry runs outputs
  libmamba/src/core/shell_init.cpp
Labels: release::bug_fixes

#3682 maint: Add pre-commit typos back
  .pre-commit-config.yaml
Labels: release::ci_docs

#3686 docs: Clarify installation of lock file
  README.md
  docs/source/user_guide/micromamba.rst
Labels: release::ci_docs

#3685 build: Remove server
  dev/CMakePresetsMamba.json
  micromamba/CMakeLists.txt
  micromamba/src/microserver.cpp
  micromamba/src/server.cpp
  micromamba/src/umamba.cpp
  micromamba/src/umamba.hpp
Labels: release::ci_docs

#3681 Fix channel in `PackageInfo`
  libmamba/src/core/package_fetcher.cpp
  libmamba/src/download/downloader.cpp
  libmamba/src/specs/package_info.cpp
  libmamba/tests/src/specs/test_package_info.cpp
Labels: release::bug_fixes

#3697 docs: Document slight differences for environment export
  README.md
Labels: release::ci_docs

#3696 Add `no-pip` flag to `list` command
  libmamba/include/mamba/api/list.hpp
  libmamba/include/mamba/core/prefix_data.hpp
  libmamba/src/api/list.cpp
  libmamba/src/core/prefix_data.cpp
  micromamba/src/list.cpp
  micromamba/tests/test_list.py
Labels: release::enhancements

#3692 Always add `root_prefix/envs` in `envs_dirs`
  libmamba/src/api/configuration.cpp
  libmamba/tests/src/core/test_configuration.cpp
  micromamba/src/common_options.hpp
  micromamba/tests/test_info.py
Labels: release::bug_fixes

#3704 docs: Use a portable web request for Windows
  docs/source/installation/micromamba-installation.rst
Labels: release::ci_docs
