Repository mamba-org/mamba, pull requests merged in 2024-05, with the labels that each got.

#3286 Test with xtensor-python instead of unmaintained xframe
  .github/workflows/unix_impl.yml
  dev/environment-dev.yml
  micromamba/tests/test_create.py
  micromamba/tests/test_env-lock.yaml
  micromamba/tests/test_env.py
  micromamba/tests/test_install.py
  micromamba/tests/test_linking.py
  micromamba/tests/test_remove.py
  micromamba/tests/test_repoquery.py
  micromamba/tests/test_update.py
Labels: release::ci_docs

#3285 Hotfix to allow Ctrl+C in python scipts
  .gitignore
  libmamba/include/mamba/core/thread_utils.hpp
  libmamba/src/core/context.cpp
  libmamba/src/core/thread_utils.cpp
Labels: release::bug_fixes

#3296 Fix OCIMirror use
  libmamba/include/mamba/download/mirror.hpp
  libmamba/include/mamba/download/request.hpp
  libmamba/src/core/package_fetcher.cpp
  libmamba/src/download/curl.cpp
  libmamba/src/download/downloader.cpp
  libmamba/src/download/downloader_impl.hpp
  libmamba/src/download/mirror.cpp
  libmamba/src/download/mirror_impl.cpp
  libmamba/src/download/mirror_impl.hpp
  libmamba/src/util/url.cpp
  libmamba/tests/src/core/test_mirror.cpp
Labels: release::enhancements

#3282 [CEP-15] Support `base_url` with `repodata_version: 2` using `mamba` parser
  libmamba/src/api/configuration.cpp
  libmamba/src/api/install.cpp
  libmamba/src/solver/libsolv/helpers.cpp
  libmamba/src/specs/package_info.cpp
  libmamba/tests/data/repodata/conda-forge-repodata-version-2-missing-base_url.json
  libmamba/tests/data/repodata/conda-forge-repodata-version-2.json
  libmamba/tests/src/solver/libsolv/test_database.cpp
Labels: release::enhancements

#3300 [OCI Registry] Handle compressed repodata
  libmamba/include/mamba/download/mirror.hpp
  libmamba/src/api/configuration.cpp
  libmamba/src/download/compression.cpp
  libmamba/src/download/compression.hpp
  libmamba/src/download/downloader.cpp
  libmamba/src/download/mirror.cpp
  libmamba/src/download/mirror_impl.cpp
  libmamba/src/download/mirror_impl.hpp
Labels: release::enhancements
