Repository mamba-org/mamba, pull requests merged in 2024-06, with the labels that each got.

#3308 Fix osx version test
  libmamba/tests/src/util/test_os_osx.cpp
Labels: release::bug_fixes

#3305 docs: Add note about `ccache`
  docs/source/developer_zone/dev_environment.rst
Labels: release::ci_docs

#3306 Fix release scripts
  releaser.py
  update_changelog.py
Labels: release::bug_fixes

#3315 Fix CI failure on win-64
  .github/workflows/static_build.yml
Labels: release::ci_docs

#3319 Fix test_no_python_pinning
  micromamba/tests/test_install.py
Labels: release::bug_fixes

#3307 [OCI - Mirrors] Add tests and doc
  docs/source/developer_zone/changes-2.0.rst
  docs/source/developer_zone/dev_environment.rst
  libmamba/include/mamba/download/request.hpp
  libmamba/src/download/mirror_impl.cpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/src/core/test_mirror.cpp
  libmamba/tests/src/download/test_mirror.cpp
  micromamba/tests/test_create.py
Labels: release::enhancements

#3310 OCI/Conda mapping
  libmamba/src/download/mirror_impl.cpp
  micromamba/tests/test_create.py
Labels: release::enhancements

#3318 maint: Remove `PrefixData::load`
  libmamba/src/core/prefix_data.cpp
Labels: release::enhancements

#3320 maint: Remove some warnings
  libmamba/src/api/install.cpp
  libmamba/src/api/shell.cpp
  libmamba/src/core/activation.cpp
  libmamba/src/core/query.cpp
  libmamba/tests/src/solver/test_problems_graph.cpp
Labels: release::enhancements

#3309 libmambapy: use `Context` explicitly
  docs/source/developer_zone/changes-2.0.rst
  libmamba/include/mamba/core/context.hpp
  libmamba/src/api/install.cpp
  libmamba/src/core/context.cpp
  libmamba/tests/src/core/test_execution.cpp
  libmambapy/src/libmambapy/__init__.pyi
  libmambapy/src/libmambapy/bindings/legacy.cpp
  libmambapy/tests/test_legacy.py
Labels: type::bug, backward incompatible, release::bug_fixes

#3322 Temporarily disabled no_python_pinning test on Windows
  micromamba/tests/test_install.py
Labels: release::ci_docs

#3325 maint: Remove declaration of `PrefixData::load`
  libmamba/include/mamba/core/prefix_data.hpp
Labels: release::enhancements
