Repository mamba-org/mamba, pull requests merged in 2024-11, with the labels that each got.

#3581 Adds logs clarifying the source of the error "could not load prefix data
  libmamba/src/api/install.cpp
  libmamba/src/api/list.cpp
  libmamba/src/api/remove.cpp
Labels: type::cleanup, release::enhancements

#3580 fix: Skip misformatted configuration files
  libmamba/src/api/configuration.cpp
  libmamba/tests/src/core/test_configuration.cpp
Labels: release::bug_fixes

#3584 Fix: json parsing error due to wrong encoding of Python output
  .github/workflows/static_build.yml
  libmamba/src/core/prefix_data.cpp
Labels: type::cleanup, release::enhancements

#3592 fixed incorrect syntax in static_build.yml
  .github/workflows/static_build.yml
Labels: what::ci, release::bug_fixes

#3586 Force spinx v6 in readthedocs
  docs/environment.yml
Labels: release::ci_docs

#3599 Update pre-commit hooks except clang-format
  .pre-commit-config.yaml
  docs/source/usage/specs.rst
  libmamba/include/mamba/util/string.hpp
  libmamba/src/core/singletons.cpp
  micromamba/tests/test_env.py
Labels: release::ci_docs

#3597 Remove Taskfile from `environment-dev-extra.yml`
  dev/environment-dev-extra.yml
Labels: release::bug_fixes

#3595 Fix some warnings
  libmamba/include/mamba/core/output.hpp
  libmamba/include/mamba/solver/libsolv/unsolvable.hpp
  libmamba/src/api/list.cpp
  libmamba/src/core/output.cpp
  libmamba/src/core/progress_bar_impl.cpp
  libmamba/src/core/shell_init.cpp
  libmamba/src/download/downloader.cpp
  libmamba/tests/src/download/test_mirror.cpp
Labels: release::bug_fixes

#3604 More details in error message when failing to parse json from a python command's output
  libmamba/include/mamba/specs/build_number_spec.hpp
  libmamba/include/mamba/specs/version_spec.hpp
  libmamba/src/core/prefix_data.cpp
Labels: release::enhancements

#3587 fix: Export `'channels'` as part of environments' export
  micromamba/src/env.cpp
  micromamba/tests/test_env.py
Labels: release::bug_fixes

#3605 maint: Address compiler warnings
  libmamba/include/mamba/util/parsers.hpp
  libmamba/src/core/prefix_data.cpp
  libmamba/src/core/progress_bar_impl.cpp
  libmamba/tests/src/validation/test_update_framework_v0_6.cpp
  micromamba/src/constructor.cpp
Labels: release::bug_fixes

#3610 docs: Update pieces of documentation after the release of mamba 2
  README.md
  docs/source/developer_zone/changes-2.0.rst
  docs/source/index.rst
Labels: release::ci_docs

#3607 Prevent pip "rich" ouput
  libmamba/src/core/prefix_data.cpp
Labels: release::bug_fixes

#3616 maint: Unify `cmake` calls in workflows, build win static builds in p…
  .github/workflows/conda_canary.yml
  .github/workflows/static_build.yml
  .github/workflows/windows_impl.yml
Labels: release::ci_docs

#3614 maint: Add dependabot config for GitHub workflows/actions
  .github/dependabot.yml
Labels: release::ci_docs

#3499 doc: Homebrew currently only installs micromamba v1
  docs/source/installation/micromamba-installation.rst
Labels: release::ci_docs

#3517 Doc: how to install specific Micromamba version
  docs/source/installation/micromamba-installation.rst
Labels: release::ci_docs

#3384 doc: show how to use advanced match specs in yaml spec
  docs/source/user_guide/micromamba.rst
Labels: release::ci_docs

#3622 fixed: incorrect erasing of env vars
  libmamba/src/core/activation.cpp
Labels: release::bug_fixes

#3619 Fix build trailing `*` display
  libmamba/src/solver/problems_graph.cpp
  libmamba/tests/src/solver/libsolv/test_solver.cpp
Labels: release::bug_fixes

#3611 maint: Enable `-Werror` compiler flag for GCC, Clang and AppleClang
  CMakeLists.txt
  cmake/CompilerWarnings.cmake
  libmamba/CMakeLists.txt
  libmamba/ext/solv-cpp/src/pool.cpp
  libmamba/include/mamba/util/conditional.hpp
  libmamba/src/core/run.cpp
  libmamba/src/core/thread_utils.cpp
  libmamba/src/core/util.cpp
  libmamba/src/solver/libsolv/matcher.cpp
  libmamba/src/solver/problems_graph.cpp
  libmambapy/CMakeLists.txt
Labels: release::bug_fixes

#3613 fix: support homebrew/linuxbrew (AppleClang, GCC 11)
  libmamba/CMakeLists.txt
  libmamba/ext/solv-cpp/CMakeLists.txt
  libmamba/include/mamba/specs/channel.hpp
  libmamba/src/core/transaction.cpp
  libmamba/src/solver/problems_graph.cpp
Labels: release::bug_fixes

#3625 ci: add brew toolchain test
  .github/workflows/brew.yml
  .github/workflows/tests.yml
Labels: release::ci_docs

#3627 fix: Return JSON on environment creation dry run
  libmamba/src/api/create.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes
