Repository mamba-org/mamba, pull requests merged in 2024-09, with the labels that each got.

#3428 Fix output
  libmamba/src/core/transaction.cpp
Labels: release::bug_fixes

#3419 fix: PyPI support for `env update`
  libmamba/CMakeLists.txt
  libmamba/src/api/install.cpp
  libmamba/src/api/pip_utils.cpp
  libmamba/src/api/pip_utils.hpp
  libmamba/src/api/update.cpp
  micromamba/tests/env-pypi-pkg-test.yaml
  micromamba/tests/test_env.py
Labels: release::bug_fixes

#3436 Fixed micromamba static build after cctools and ld64 upgrade on conda…
  libmamba/CMakeLists.txt
  micromamba/CMakeLists.txt
Labels: release::bug_fixes

#3433 Fix x86_64 to use underscore instead of dash
  libmamba/src/core/virtual_packages.cpp
Labels: release::bug_fixes

#3438 docs: Specify `CMAKE_INSTALL_PREFIX`
  docs/source/installation/micromamba-installation.rst
Labels: release::ci_docs

#3434 fix: add warning when using defaults
  .github/workflows/static_build.yml
  dev/environment-dev.yml
  dev/environment-micromamba-static.yml
  libmamba/include/mamba/core/context.hpp
  libmamba/src/api/channel_loader.cpp
  libmamba/src/api/configuration.cpp
  libmambapy/src/libmambapy/bindings/legacy.cpp
Labels: release::bug_fixes

#3442 Remove cctools patch from feedstock in CI
  .github/workflows/static_build.yml
Labels: release::enhancements

#3448 Fix test in osx
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3450 fix: Environment removal confirmation
  libmamba/include/mamba/api/remove.hpp
  libmamba/src/api/remove.cpp
  micromamba/src/env.cpp
Labels: release::bug_fixes

#3462 Fix wrong version of miniforge in doc
  docs/source/installation/mamba-installation.rst
Labels: release::ci_docs

#3459 Fix `test_env_update_pypi_with_conda_forge`
  micromamba/tests/test_env.py
Labels: release::bug_fixes

#3445 Support CONDA_DEFAULT_ENV
  libmamba/src/api/clean.cpp
  libmamba/src/api/config.cpp
  libmamba/src/api/configuration.cpp
  libmamba/src/api/create.cpp
  libmamba/src/api/info.cpp
  libmamba/src/api/install.cpp
  libmamba/src/api/list.cpp
  libmamba/src/api/remove.cpp
  libmamba/src/api/repoquery.cpp
  libmamba/src/api/update.cpp
  micromamba/src/config.cpp
  micromamba/src/constructor.cpp
  micromamba/src/shell.cpp
  micromamba/tests/test_create.py
  micromamba/tests/test_install.py
  micromamba/tests/test_remove.py
  micromamba/tests/test_shell.py
  micromamba/tests/test_update.py
Labels: release::enhancements

#3456 fix: Handle extra white-space in `MatchSpec`
  libmamba/src/specs/match_spec.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  micromamba/tests/env-extra-white-space.yaml
  micromamba/tests/test_env.py
Labels: release::bug_fixes

#3447 Compute `root prefix` as mamba install path
  .github/workflows/unix_impl.yml
  .github/workflows/windows_impl.yml
  libmamba/CMakeLists.txt
  libmamba/src/api/configuration.cpp
Labels: release::enhancements

#3458 test: `MatchSpec` edges cases
  libmamba/tests/src/specs/test_match_spec.cpp
Labels: release::bug_fixes

#3466 Apply feedstock patches
  libmamba/CMakeLists.txt
  mamba_package/CMakeLists.txt
  micromamba/CMakeLists.txt
Labels: 1.x

#3471 doc: add github links to documentation
  CONTRIBUTING.rst
  docs/source/conf.py
Labels: release::ci_docs

#3474 Added --copy flag to create and install commands
  micromamba/src/common_options.cpp
Labels: release::bug_fixes

#3484 Fix micromamba activate on Windows
  libmamba/data/mamba_hook.bat
Labels: release::bug_fixes

#3483 fix: Support for PEP 440 "Compatible Releases" (operator `~=` for `MatchSpec`)
  libmamba/src/specs/match_spec.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  micromamba/tests/test_install.py
Labels: release::bug_fixes

#3485 --full-name option for list
  libmamba/include/mamba/api/list.hpp
  libmamba/src/api/list.cpp
  micromamba/src/list.cpp
  micromamba/tests/test_list.py
Labels: release::bug_fixes
