Repository mamba-org/mamba, pull requests merged in 2024-03, with the labels that each got.

#3207 Expected in specs parse API
  libmamba/include/mamba/specs/channel.hpp
  libmamba/include/mamba/specs/conda_url.hpp
  libmamba/include/mamba/specs/match_spec.hpp
  libmamba/include/mamba/specs/package_info.hpp
  libmamba/src/api/channel_loader.cpp
  libmamba/src/api/install.cpp
  libmamba/src/api/remove.cpp
  libmamba/src/api/update.cpp
  libmamba/src/core/channel_context.cpp
  libmamba/src/core/env_lockfile.cpp
  libmamba/src/core/history.cpp
  libmamba/src/core/output.cpp
  libmamba/src/core/package_cache.cpp
  libmamba/src/core/pinning.cpp
  libmamba/src/core/prefix_data.cpp
  libmamba/src/core/query.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/solver/libsolv/helpers.cpp
  libmamba/src/solver/libsolv/unsolvable.cpp
  libmamba/src/specs/channel.cpp
  libmamba/src/specs/conda_url.cpp
  libmamba/src/specs/match_spec.cpp
  libmamba/src/specs/package_info.cpp
  libmamba/src/validation/update_framework_v0_6.cpp
  libmamba/tests/src/solver/libsolv/test_database.cpp
  libmamba/tests/src/solver/libsolv/test_solver.cpp
  libmamba/tests/src/specs/test_channel.cpp
  libmamba/tests/src/specs/test_conda_url.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmamba/tests/src/specs/test_package_info.cpp
  micromamba/src/constructor.cpp
  micromamba/src/env.cpp
  micromamba/src/update.cpp
  micromamba/tests/test_install.py
Labels: release::enhancements

#3211 Add more MatchSpec tests
  libmamba/tests/src/specs/test_match_spec.cpp
Labels: release::enhancements

#3213 Fully bind MatchSpec
  libmamba/src/specs/match_spec.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmambapy/src/libmambapy/bindings/specs.cpp
  libmambapy/tests/test_specs.py
Labels: release::enhancements

#3214 Subdir renaming
  libmamba/include/mamba/specs/build_number_spec.hpp
  libmamba/include/mamba/specs/conda_url.hpp
  libmamba/include/mamba/specs/match_spec.hpp
  libmamba/include/mamba/specs/package_info.hpp
  libmamba/include/mamba/specs/platform.hpp
  libmamba/include/mamba/specs/repo_data.hpp
  libmamba/include/mamba/specs/unresolved_channel.hpp
  libmamba/src/api/list.cpp
  libmamba/src/core/env_lockfile.cpp
  libmamba/src/core/link.cpp
  libmamba/src/core/package_fetcher.cpp
  libmamba/src/core/prefix_data.cpp
  libmamba/src/core/query.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/core/virtual_packages.cpp
  libmamba/src/solver/libsolv/helpers.cpp
  libmamba/src/specs/conda_url.cpp
  libmamba/src/specs/match_spec.cpp
  libmamba/src/specs/package_info.cpp
  libmamba/src/specs/platform.cpp
  libmamba/src/specs/unresolved_channel.cpp
  libmamba/tests/src/core/test_virtual_packages.cpp
  libmamba/tests/src/solver/libsolv/test_database.cpp
  libmamba/tests/src/solver/libsolv/test_solver.cpp
  libmamba/tests/src/solver/test_problems_graph.cpp
  libmamba/tests/src/specs/test_conda_url.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmamba/tests/src/specs/test_package_info.cpp
  libmamba/tests/src/specs/test_platform.cpp
  libmamba/tests/src/specs/test_repo_data.cpp
  libmambapy/src/libmambapy/bindings/specs.cpp
  libmambapy/tests/test_solver_libsolv.py
  libmambapy/tests/test_specs.py
  micromamba/src/env.cpp
Labels: release::enhancements

#3224 Add MatchSpec doc and fix errors
  .pre-commit-config.yaml
  docs/source/advanced_usage/detailed_operations.rst
  docs/source/advanced_usage/package_resolution.rst
  docs/source/developer_zone/changes-2.0.rst
  docs/source/developer_zone/dev_environment.rst
  docs/source/index.rst
  docs/source/installation/mamba-installation.rst
  docs/source/python_api.rst
  docs/source/usage/solver.rst
  docs/source/usage/specs.rst
  docs/source/user_guide/configuration.rst
  docs/source/user_guide/troubleshooting.rst
Labels: what::documentation, release::ci_docs

#3215 Refactor MatchSpec::str
  libmamba/include/mamba/specs/match_spec.hpp
  libmamba/include/mamba/specs/unresolved_channel.hpp
  libmamba/include/mamba/specs/version_spec.hpp
  libmamba/include/mamba/util/string.hpp
  libmamba/src/specs/match_spec.cpp
  libmamba/src/specs/unresolved_channel.cpp
  libmamba/src/specs/version_spec.cpp
  libmamba/src/util/string.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmamba/tests/src/util/test_string.cpp
  libmambapy/tests/test_specs.py
Labels: release::enhancements

#3192 [mamba content trust] Enable verifying packages signatures
  libmamba/CMakeLists.txt
  libmamba/ext/solv-cpp/include/solv-cpp/solvable.hpp
  libmamba/ext/solv-cpp/src/solvable.cpp
  libmamba/ext/solv-cpp/tests/src/test_solvable.cpp
  libmamba/include/mamba/core/context.hpp
  libmamba/include/mamba/core/package_cache.hpp
  libmamba/include/mamba/core/package_handling.hpp
  libmamba/include/mamba/core/repo_checker_store.hpp
  libmamba/include/mamba/solver/libsolv/database.hpp
  libmamba/include/mamba/solver/libsolv/parameters.hpp
  libmamba/include/mamba/validation/errors.hpp
  libmamba/include/mamba/validation/repo_checker.hpp
  libmamba/include/mamba/validation/update_framework.hpp
  libmamba/include/mamba/validation/update_framework_v0_6.hpp
  libmamba/include/mamba/validation/update_framework_v1.hpp
  libmamba/src/api/configuration.cpp
  libmamba/src/core/package_cache.cpp
  libmamba/src/core/package_database_loader.cpp
  libmamba/src/core/package_handling.cpp
  libmamba/src/core/repo_checker_store.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/solver/libsolv/database.cpp
  libmamba/src/solver/libsolv/helpers.cpp
  libmamba/src/solver/libsolv/helpers.hpp
  libmamba/src/specs/package_info.cpp
  libmamba/src/validation/errors.cpp
  libmamba/src/validation/repo_checker.cpp
  libmamba/src/validation/update_framework_v0_6.cpp
  libmamba/src/validation/update_framework_v1.cpp
  libmamba/tests/data/repodata/conda-forge-numpy-linux-64.json
  libmamba/tests/src/solver/libsolv/test_database.cpp
  libmamba/tests/src/specs/test_package_info.cpp
  libmambapy/src/libmambapy/bindings/legacy.cpp
  libmambapy/src/libmambapy/bindings/solver_libsolv.cpp
  libmambapy/tests/test_solver_libsolv.py
  micromamba/src/common_options.cpp
Labels: release::enhancements

#3231 Add MatchSpec::contains_except_channel"
  docs/source/usage/specs.rst
  libmamba/include/mamba/specs/match_spec.hpp
  libmamba/src/specs/match_spec.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmambapy/src/libmambapy/bindings/specs.cpp
  libmambapy/tests/test_specs.py
Labels: release::enhancements

#3220 fix(micromamba): anaconda private channels not working
  libmamba/src/core/context.cpp
Labels: release::bug_fixes

#3225 Mamba 2.0 name fixes
  libmamba/CMakeLists.txt
  libmamba/data/Mamba.psm1
  libmamba/data/_mamba_activate.bat
  libmamba/data/activate.bat
  libmamba/data/mamba.bat
  libmamba/data/mamba.csh
  libmamba/data/mamba.sh
  libmamba/data/mamba_hook.bat
  libmamba/include/mamba/core/context.hpp
  libmamba/include/mamba/core/package_handling.hpp
  libmamba/include/mamba/core/shell_init.hpp
  libmamba/include/mamba/core/util.hpp
  libmamba/src/api/configuration.cpp
  libmamba/src/api/info.cpp
  libmamba/src/core/activation.cpp
  libmamba/src/core/package_handling.cpp
  libmamba/src/core/shell_init.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/core/util.cpp
  micromamba/src/activate.cpp
  micromamba/src/main.cpp
  micromamba/tests/helpers.py
  micromamba/tests/test_activation.py
  micromamba/tests/test_shell.py
Labels: release::bug_fixes

#3235 Typos in dev_environment.rst
  docs/source/developer_zone/dev_environment.rst
Labels: release::enhancements

#3236 Fixed a spelling mistake in micromamba-installation.rst
  docs/source/installation/micromamba-installation.rst
Labels: release::ci_docs

#3233 Custom resolve complex MatchSpec in Solver
  libmamba/CMakeLists.txt
  libmamba/ext/solv-cpp/include/solv-cpp/pool.hpp
  libmamba/ext/solv-cpp/include/solv-cpp/solvable.hpp
  libmamba/ext/solv-cpp/src/pool.cpp
  libmamba/ext/solv-cpp/src/solvable.cpp
  libmamba/ext/solv-cpp/src/solver.cpp
  libmamba/ext/solv-cpp/tests/src/test_pool.cpp
  libmamba/ext/solv-cpp/tests/src/test_scenarios.cpp
  libmamba/ext/solv-cpp/tests/src/test_solvable.cpp
  libmamba/include/mamba/specs/match_spec.hpp
  libmamba/include/mamba/specs/version_spec.hpp
  libmamba/src/solver/libsolv/database.cpp
  libmamba/src/solver/libsolv/helpers.cpp
  libmamba/src/solver/libsolv/helpers.hpp
  libmamba/src/solver/libsolv/matcher.cpp
  libmamba/src/solver/libsolv/matcher.hpp
  libmamba/src/solver/libsolv/solver.cpp
  libmamba/src/solver/libsolv/unsolvable.cpp
  libmamba/src/specs/match_spec.cpp
  libmamba/src/specs/version_spec.cpp
  libmamba/tests/src/solver/libsolv/test_solver.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmamba/tests/src/specs/test_version_spec.cpp
  libmambapy/src/libmambapy/bindings/specs.cpp
  libmambapy/tests/test_solver_libsolv.py
  libmambapy/tests/test_specs.py
  micromamba/tests/test_create.py
Labels: release::enhancements

#3238 Release libsolv memory before installation
  libmamba/src/api/install.cpp
Labels: release::enhancements

#3234 [mamba-content-trust] Add integration test
  .github/workflows/unix_impl.yml
  Taskfile.dist.yml
  libmamba/include/mamba/core/context.hpp
  libmamba/include/mamba/core/repo_checker_store.hpp
  libmamba/src/core/repo_checker_store.cpp
  libmamba/src/core/transaction.cpp
  micromamba/test-server/repo/noarch/current_repodata.json
  micromamba/test-server/repo/noarch/current_repodata.json.bz2
  micromamba/test-server/repo/noarch/repodata.json
  micromamba/test-server/repo/noarch/repodata.json.bz2
  micromamba/test-server/repo/noarch/repodata_from_packages.json
  micromamba/test-server/repo/noarch/repodata_from_packages.json.bz2
  micromamba/test-server/repo/noarch/test-package-0.1-0.tar.bz2
  micromamba/test-server/repo_signed/1.root.json
  micromamba/test-server/repo_signed/key_mgr.json
  micromamba/test-server/repo_signed/noarch/repodata.json
  micromamba/test-server/reposerver.py
  micromamba/test-server/testserver_pkg_signing.sh
Labels: release::enhancements

#3239 Handle regex in build string
  libmamba/CMakeLists.txt
  libmamba/include/mamba/specs/chimera_string_spec.hpp
  libmamba/include/mamba/specs/match_spec.hpp
  libmamba/include/mamba/specs/regex_spec.hpp
  libmamba/src/core/transaction.cpp
  libmamba/src/solver/libsolv/helpers.cpp
  libmamba/src/solver/problems_graph.cpp
  libmamba/src/specs/chimera_string_spec.cpp
  libmamba/src/specs/match_spec.cpp
  libmamba/src/specs/regex_spec.cpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/src/specs/test_chimera_string_spec.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmamba/tests/src/specs/test_regex_spec.cpp
  libmambapy/src/libmambapy/bindings/specs.cpp
  libmambapy/tests/test_specs.py
Labels: release::enhancements

#3245 Passed url_path to request_generators
  libmamba/include/mamba/download/mirror.hpp
  libmamba/src/download/downloader.cpp
  libmamba/src/download/downloader_impl.hpp
  libmamba/src/download/mirror.cpp
  libmamba/src/download/mirror_impl.cpp
  libmamba/src/download/mirror_impl.hpp
Labels: release::enhancements

#3249 Use conda-forge feedstock for static builds
  .github/workflows/static_build.yml
Labels: release::bug_fixes

#3246 Implemented OCI mirrors
  libmamba/include/mamba/core/error_handling.hpp
  libmamba/include/mamba/download/mirror.hpp
  libmamba/src/download/downloader.cpp
  libmamba/src/download/mirror.cpp
  libmamba/src/download/mirror_impl.cpp
  libmamba/src/download/mirror_impl.hpp
Labels: release::enhancements

#3248 Refactor os utilities
  libmamba/CMakeLists.txt
  libmamba/include/mamba/core/util_os.hpp
  libmamba/include/mamba/core/virtual_packages.hpp
  libmamba/include/mamba/specs/platform.hpp
  libmamba/include/mamba/util/os.hpp
  libmamba/include/mamba/util/os_linux.hpp
  libmamba/include/mamba/util/os_osx.hpp
  libmamba/include/mamba/util/os_unix.hpp
  libmamba/include/mamba/util/os_win.hpp
  libmamba/src/core/util_os.cpp
  libmamba/src/core/virtual_packages.cpp
  libmamba/src/specs/platform.cpp
  libmamba/src/util/os_linux.cpp
  libmamba/src/util/os_osx.cpp
  libmamba/src/util/os_unix.cpp
  libmamba/src/util/os_win.cpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/src/core/test_virtual_packages.cpp
  libmamba/tests/src/specs/test_platform.cpp
  libmamba/tests/src/util/test_os_linux.cpp
  libmamba/tests/src/util/test_os_osx.cpp
  libmamba/tests/src/util/test_os_unix.cpp
  libmamba/tests/src/util/test_os_win.cpp
  micromamba/tests/test_create.py
Labels: release::enhancements

#3253 Don't add duplicate .conda and .tar.bz2 packages
  libmamba/include/mamba/solver/libsolv/database.hpp
  libmamba/include/mamba/solver/libsolv/parameters.hpp
  libmamba/src/core/package_database_loader.cpp
  libmamba/src/solver/libsolv/database.cpp
  libmamba/src/solver/libsolv/helpers.cpp
  libmamba/src/solver/libsolv/helpers.hpp
  libmamba/src/solver/problems_graph.cpp
  libmamba/tests/data/repodata/conda-forge-numpy-linux-64.json
  libmamba/tests/src/solver/libsolv/test_database.cpp
  libmambapy/src/libmambapy/bindings/solver_libsolv.cpp
  libmambapy/tests/test_solver_libsolv.py
Labels: release::bug_fixes

#3254 Small changelog additions
  docs/source/developer_zone/changes-2.0.rst
Labels: release::ci_docs

#3255 Bind VersionPredicate
  libmambapy/src/libmambapy/bindings/specs.cpp
  libmambapy/tests/test_specs.py
Labels: release::enhancements

#3256 Add missing pybind header
  libmambapy/src/libmambapy/bindings/solver_libsolv.cpp
  libmambapy/tests/test_solver_libsolv.py
Labels: release::bug_fixes
