Repository mamba-org/mamba, pull requests merged in 2025-02, with the labels that each got.

#3769 ci: Rerun pytest tests on `main` in case of failures
  .github/workflows/unix_impl.yml
  .github/workflows/windows_impl.yml
  dev/environment-dev.yml
Labels: release::ci_docs

#3792 fix: Use `libmamba`'s installation instead of `mamba`'s as a fallback
  libmamba/src/api/configuration.cpp
Labels: release::bug_fixes

#3788 maint: Warn about future removal of `etc/profile.d/mamba.sh`
  micromamba/etc/profile.d/mamba.sh.in
Labels: release::bug_fixes

#3780 feat: add export flag to list command
  libmamba/src/api/list.cpp
  micromamba/src/list.cpp
  micromamba/tests/test_list.py
Labels: release::enhancements

#3783 docs: Document that mamba 2 only supports trailing globs in version strings
  docs/source/developer_zone/changes-2.0.rst
Labels: release::ci_docs

#3794 [Windows] Write command in multiple lines
  .github/workflows/windows_impl.yml
Labels: release::ci_docs

#3801 Add missing config for RTD
  .readthedocs.yml
Labels: release::ci_docs

#3818 fix: Adaptive level for compatible Version formatting
  libmamba/src/specs/match_spec.cpp
  libmamba/src/specs/version_spec.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmamba/tests/src/specs/test_version_spec.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3787 Fix windows paths and add tests
  libmamba/include/mamba/fs/filesystem.hpp
  libmamba/src/core/link.cpp
  libmamba/src/fs/filesystem.cpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/src/core/test_filesystem.cpp
  libmamba/tests/src/core/test_transaction_context.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3823 ci: Also run workflows for `feat/*` branches
  .github/workflows/linters.yml
  .github/workflows/static_build.yml
  .github/workflows/tests.yml
Labels: release::ci_docs

#3813 fix: Adapt root prefix' precedence for `envs_dirs`
  libmamba/include/mamba/api/configuration_impl.hpp
  libmamba/src/core/context.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3829 fix: Explain unsolvable updates
  libmamba/src/api/update.cpp
  micromamba/tests/test_update.py
Labels: release::bug_fixes

#3779 feat: add base flag to info command
  libmamba/src/api/info.cpp
  libmamba/src/api/list.cpp
  micromamba/src/info.cpp
  micromamba/tests/test_info.py
Labels: release::bug_fixes

#3833 maint: Remove unused structure in update path
  libmamba/src/api/update.cpp
Labels: release::ci_docs

#3816 Use correct `url` in metadata and mirrors
  docs/source/developer_zone/changes-2.0.rst
  libmamba/include/mamba/core/package_fetcher.hpp
  libmamba/include/mamba/core/subdirdata.hpp
  libmamba/src/core/package_fetcher.cpp
  libmamba/src/core/subdirdata.cpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/src/core/test_package_fetcher.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3756 maint: Add markdownlint pre-commit hook
  .markdownlint.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  README.md
  libmamba/CHANGELOG.md
  libmambapy/CHANGELOG.md
  micromamba/CHANGELOG.md
  micromamba/tests/pre_commit_conda_hooks_repo/README.md
  releaser.py
  update_changelog.py
Labels: release::ci_docs

#3803 fix: Add `x86_64` archspec support for Windows
  libmamba/src/core/virtual_packages.cpp
Labels: release::bug_fixes

#3838 fix: Temporarily skip `test_pip_git_https_lockfile`
  micromamba/tests/test_create.py
Labels: release::ci_docs

#3843 ci: Add "release::maintenance" Pull Request label
  .github/workflows/label_check.yml
  update_changelog.py
Labels: release::ci_docs

#3796 fix: Create directories from `envs_dirs` if they do not exist
  libmamba/src/api/configuration.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes
