Repository mamba-org/mamba, pull requests merged in 2025-04, with the labels that each got.

#3876 ci: Add minimal code coverage workflow
  .github/workflows/coverage.yml
  dev/environment-dev.yml
  libmamba/tests/src/util/test_cast.cpp
Labels: release::maintenance

#3882 Bind package extraction
  libmambapy/src/libmambapy/bindings/legacy.cpp
Labels: release::enhancements

#3875 Fix install using remote yaml files
  libmamba/include/mamba/api/install.hpp
  libmamba/src/api/install.cpp
  libmamba/tests/src/core/test_env_file_reading.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3890 ci: Adapt code coverage workflow
  .github/workflows/coverage.yml
Labels: release::maintenance

#3899 Ready Libsolv for C++20
  libmamba/ext/solv-cpp/CMakeLists.txt
  libmamba/ext/solv-cpp/src/solvable.cpp
Labels: release::maintenance

#3889 Fix VersionSpec globs
  docs/source/developer_zone/changes-2.0.rst
  libmamba/include/mamba/specs/version.hpp
  libmamba/include/mamba/specs/version_spec.hpp
  libmamba/src/specs/match_spec.cpp
  libmamba/src/specs/version.cpp
  libmamba/src/specs/version_spec.cpp
  libmamba/src/specs/version_spec_impl.hpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmamba/tests/src/specs/test_version.cpp
  libmamba/tests/src/specs/test_version_spec.cpp
  libmambapy/src/libmambapy/bindings/specs.cpp
Labels: release::bug_fixes

#3878 Use Simdjson ondemand parser instead of DOM parser
  libmamba/include/mamba/util/flat_set.hpp
  libmamba/src/solver/libsolv/helpers.cpp
  libmamba/tests/src/util/test_flat_set.cpp
Labels: release::enhancements

#3900 Some test isolation
  micromamba/tests/test_create.py
Labels: release::maintenance

#3906 Make `self-update` a command for micromamba only
  micromamba/CMakeLists.txt
  micromamba/src/umamba.cpp
  micromamba/src/umamba.hpp
  micromamba/src/update.cpp
  micromamba/tests/test_activation.py
Labels: release::bug_fixes

#3910 fix: Requalify warning when parsing the "mod/etag" header
  libmamba/src/core/subdirdata.cpp
Labels: release::bug_fixes

#3912 Fix segfault in error messages
  libmamba/src/solver/libsolv/unsolvable.cpp
  libmamba/src/solver/problems_graph.cpp
  libmamba/tests/data/repodata/sudoku.json
  libmamba/tests/src/solver/test_problems_graph.cpp
Labels: release::bug_fixes

#3914 Add minimal citation information for mamba
  CITATION.cff
Labels: release::ci_docs
