Repository mamba-org/mamba, pull requests merged in 2025-05, with the labels that each got.

#3913 Explicit API and ABI stability commitments
  README.md
Labels: release::ci_docs

#3915 Remove implicit zero in Version formatting
  libmamba/include/mamba/specs/version.hpp
  libmamba/src/specs/version.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmamba/tests/src/specs/test_version.cpp
  libmambapy/src/libmambapy/bindings/specs.cpp
  libmambapy/tests/test_specs.py
Labels: release::bug_fixes

#3907 Matchspec hardening
  libmamba/include/mamba/core/context.hpp
  libmamba/include/mamba/solver/libsolv/database.hpp
  libmamba/include/mamba/solver/libsolv/solver.hpp
  libmamba/src/api/configuration.cpp
  libmamba/src/api/install.cpp
  libmamba/src/api/remove.cpp
  libmamba/src/api/repoquery.cpp
  libmamba/src/api/update.cpp
  libmamba/src/solver/libsolv/database.cpp
  libmamba/src/solver/libsolv/solver.cpp
  libmamba/tests/src/solver/libsolv/test_database.cpp
  libmamba/tests/src/solver/libsolv/test_solver.cpp
  libmamba/tests/src/solver/test_request.cpp
  libmamba/tests/src/solver/test_solution.cpp
  libmambapy/src/libmambapy/bindings/solver_libsolv.cpp
  libmambapy/tests/test_legacy.py
  libmambapy/tests/test_solver_libsolv.py
Labels: release::maintenance

#3917 Rename str > to_string
  libmamba/include/mamba/specs/build_number_spec.hpp
  libmamba/include/mamba/specs/chimera_string_spec.hpp
  libmamba/include/mamba/specs/glob_spec.hpp
  libmamba/include/mamba/specs/match_spec.hpp
  libmamba/include/mamba/specs/package_info.hpp
  libmamba/include/mamba/specs/regex_spec.hpp
  libmamba/include/mamba/specs/version.hpp
  libmamba/include/mamba/specs/version_spec.hpp
  libmamba/src/api/install.cpp
  libmamba/src/api/remove.cpp
  libmamba/src/api/update.cpp
  libmamba/src/core/history.cpp
  libmamba/src/core/link.cpp
  libmamba/src/core/prefix_data.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/solver/libsolv/helpers.cpp
  libmamba/src/solver/libsolv/matcher.cpp
  libmamba/src/solver/libsolv/solver.cpp
  libmamba/src/solver/libsolv/unsolvable.cpp
  libmamba/src/solver/problems_graph.cpp
  libmamba/src/specs/build_number_spec.cpp
  libmamba/src/specs/chimera_string_spec.cpp
  libmamba/src/specs/glob_spec.cpp
  libmamba/src/specs/match_spec.cpp
  libmamba/src/specs/regex_spec.cpp
  libmamba/src/specs/repo_data.cpp
  libmamba/src/specs/version.cpp
  libmamba/src/specs/version_spec.cpp
  libmamba/tests/src/solver/test_problems_graph.cpp
  libmamba/tests/src/specs/test_build_number_spec.cpp
  libmamba/tests/src/specs/test_chimera_string_spec.cpp
  libmamba/tests/src/specs/test_glob_spec.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmamba/tests/src/specs/test_regex_spec.cpp
  libmamba/tests/src/specs/test_repo_data.cpp
  libmamba/tests/src/specs/test_version.cpp
  libmamba/tests/src/specs/test_version_spec.cpp
  libmambapy/src/libmambapy/bindings/specs.cpp
  micromamba/src/env.cpp
Labels: release::maintenance

#3928 Remove Context from downloaders
  libmamba/include/mamba/core/context.hpp
  libmamba/include/mamba/download/downloader.hpp
  libmamba/include/mamba/download/parameters.hpp
  libmamba/src/api/install.cpp
  libmamba/src/core/package_fetcher.cpp
  libmamba/src/core/subdirdata.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/download/downloader.cpp
  libmamba/src/download/downloader_impl.hpp
  libmamba/src/validation/repo_checker.cpp
  libmamba/src/validation/update_framework_v0_6.cpp
  libmamba/tests/src/download/test_downloader.cpp
  libmamba/tests/src/download/test_mirror.cpp
  libmambapy/src/libmambapy/bindings/legacy.cpp
Labels: release::maintenance

#3873 fix: Avoid use-after-free in MessageLogger
  libmamba/src/core/output.cpp
Labels: release::bug_fixes

#3871 [Unix] Fix slashes usage in file urls
  libmamba/include/mamba/specs/conda_url.hpp
  libmamba/include/mamba/util/url_manip.hpp
  libmamba/src/util/url.cpp
  libmamba/src/util/url_manip.cpp
  libmamba/tests/src/specs/test_conda_url.cpp
  libmamba/tests/src/util/test_url.cpp
  libmamba/tests/src/util/test_url_manip.cpp
Labels: release::bug_fixes

#3926 Simplify SubdirData
  libmamba/include/mamba/core/context.hpp
  libmamba/include/mamba/core/subdir_parameters.hpp
  libmamba/include/mamba/core/subdirdata.hpp
  libmamba/include/mamba/specs/platform.hpp
  libmamba/src/api/channel_loader.cpp
  libmamba/src/core/package_database_loader.cpp
  libmamba/src/core/subdirdata.cpp
  libmamba/src/specs/platform.cpp
  libmamba/tests/src/core/test_cpp.cpp
  libmamba/tests/src/solver/test_problems_graph.cpp
  libmambapy/src/libmambapy/bindings/legacy.cpp
Labels: release::maintenance

#3934 Use range in subdir iteration
  libmamba/include/mamba/core/subdirdata.hpp
  libmamba/src/core/subdirdata.cpp
Labels: release::maintenance

#3930 ci: Disable GitHub annotations for Codecov in PRs
  codecov.yml
Labels: release::ci_docs

#3931 Adapt citation information for mamba
  CITATION.cff
Labels: release::maintenance

#3935 Remove temp_file from public API
  libmamba/include/mamba/core/subdirdata.hpp
  libmamba/src/core/subdirdata.cpp
Labels: release::maintenance

#3937 Load local path when offline
  libmamba/include/mamba/core/subdirdata.hpp
  libmamba/src/core/subdirdata.cpp
Labels: release::enhancements

#3919 Allow creating environment with empty folder as target prefix
  libmamba/src/api/create.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3903 Avoid ODR violation for `type_caster<mamba::fs::u8path>`
  libmambapy/src/libmambapy/bindings/path_caster.hpp
  libmambapy/src/libmambapy/bindings/specs.cpp
  libmambapy/src/libmambapy/bindings/utils.cpp
Labels: release::maintenance

#3918 support installing pip dependencies with uv
  libmamba/include/mamba/api/install.hpp
  libmamba/include/mamba/core/context.hpp
  libmamba/src/api/configuration.cpp
  libmamba/src/api/install.cpp
  libmamba/src/api/utils.cpp
  libmamba/tests/data/env_file/env_4.yaml
  libmamba/tests/src/core/test_env_file_reading.cpp
  micromamba/src/common_options.cpp
Labels: release::enhancements

#3855 Unify CONDA_ENVS_PATH, CONDA_ENVS_DIRS
  libmamba/src/api/configuration.cpp
  micromamba/tests/test_activation.py
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3932 Fix typo in help menu for the `reactivate` command
  libmamba/data/mamba.fish
  micromamba/src/shell.cpp
Labels: release::bug_fixes

#3940 Refactor `SubdirData` > `SubdirIndexLoader`
  libmamba/CMakeLists.txt
  libmamba/include/mamba/core/context.hpp
  libmamba/include/mamba/core/download_progress_bar.hpp
  libmamba/include/mamba/core/package_database_loader.hpp
  libmamba/include/mamba/core/subdir_index.hpp
  libmamba/include/mamba/core/subdir_parameters.hpp
  libmamba/src/api/channel_loader.cpp
  libmamba/src/core/download_progress_bar.cpp
  libmamba/src/core/package_database_loader.cpp
  libmamba/src/core/repo_checker_store.cpp
  libmamba/src/core/subdir_index.cpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/include/mambatests.hpp
  libmamba/tests/src/core/test_cpp.cpp
  libmamba/tests/src/core/test_filesystem.cpp
  libmamba/tests/src/core/test_subdir_index.cpp
  libmamba/tests/src/solver/test_problems_graph.cpp
  libmambapy/src/libmambapy/bindings/expected_caster.hpp
  libmambapy/src/libmambapy/bindings/legacy.cpp
  micromamba/src/constructor.cpp
Labels: release::maintenance

#3941 Fix wrong use of deprecation macro
  libmamba/include/mamba/util/deprecation.hpp
  libmamba/include/mamba/util/functional.hpp
Labels: release::bug_fixes

#3929 Fix deactivate nushell
  libmamba/src/core/shell_init.cpp
Labels: release::bug_fixes

#3944 Constexpr `fmt::formatter::parse` for C++20 with `from_chars`
  libmamba/include/mamba/specs/version.hpp
  libmamba/include/mamba/util/charconv.hpp
  libmamba/src/specs/version.cpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/src/util/test_charconv.cpp
Labels: release::maintenance

#3897 Make integration tests not rely on specific organisation of packages
  micromamba/tests/helpers.py
  micromamba/tests/test_activation.py
  micromamba/tests/test_create.py
  micromamba/tests/test_install.py
  micromamba/tests/test_linking.py
  micromamba/tests/test_pkg_cache.py
Labels: release::maintenance

#3949 Context dependency reduction
  libmamba/CMakeLists.txt
  libmamba/include/mamba/core/context.hpp
  libmamba/include/mamba/core/context_params.hpp
  libmamba/include/mamba/core/history.hpp
  libmamba/include/mamba/core/shell_init.hpp
  libmamba/include/mamba/core/util.hpp
  libmamba/src/api/utils.cpp
  libmamba/src/core/history.cpp
  libmamba/src/core/link.cpp
  libmamba/src/core/run.cpp
  libmamba/src/core/shell_init.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/core/transaction_context.cpp
  libmamba/src/core/util.cpp
  libmamba/tests/src/core/test_cpp.cpp
  libmambapy/src/libmambapy/bindings/legacy.cpp
Labels: release::maintenance

#3950 Transaction context
  libmamba/include/mamba/core/context.hpp
  libmamba/include/mamba/core/context_params.hpp
  libmamba/include/mamba/core/environments_manager.hpp
  libmamba/include/mamba/core/menuinst.hpp
  libmamba/include/mamba/core/transaction.hpp
  libmamba/include/mamba/core/transaction_context.hpp
  libmamba/include/mamba/core/util.hpp
  libmamba/src/api/configuration.cpp
  libmamba/src/api/info.cpp
  libmamba/src/api/install.cpp
  libmamba/src/api/utils.cpp
  libmamba/src/core/context.cpp
  libmamba/src/core/environments_manager.cpp
  libmamba/src/core/link.cpp
  libmamba/src/core/menuinst.cpp
  libmamba/src/core/run.cpp
  libmamba/src/core/transaction.cpp
  libmamba/src/core/transaction_context.cpp
  libmamba/src/core/util.cpp
  libmamba/tests/src/core/test_configuration.cpp
  libmamba/tests/src/core/test_cpp.cpp
  libmambapy/src/libmambapy/bindings/legacy.cpp
  micromamba/src/env.cpp
  micromamba/src/run.cpp
Labels: release::maintenance

#3892 unify channels of installed and removed packages written in history
  libmamba/src/core/transaction.cpp
  micromamba/tests/test_history.py
Labels: release::bug_fixes

#3955 Handle environment variables from `yaml` file
  libmamba/include/mamba/api/install.hpp
  libmamba/src/api/configuration.cpp
  libmamba/src/api/create.cpp
  libmamba/src/api/install.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes
