Repository mamba-org/mamba, pull requests merged in 2025-06, with the labels that each got.

#3936 Allow users to set labels on PRs
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/set_pr_label.yml
Labels: release::enhancements

#3962 Use fmt::runtime where needed in C++20
  libmamba/src/core/progress_bar_impl.cpp
  libmamba/src/solver/problems_graph.cpp
  libmamba/src/specs/version.cpp
  libmamba/src/specs/version_spec.cpp
Labels: release::maintenance

#3963 Fix listing dependencies pulled with `pip`
  libmamba/src/core/prefix_data.cpp
  micromamba/tests/test_env.py
  micromamba/tests/test_list.py
Labels: release::bug_fixes

#3965 Compile with C++20
  .clang-format
  dev/CMakePresetsMamba.json
  libmamba/CMakeLists.txt
  libmamba/ext/solv-cpp/CMakeLists.txt
  libmamba/include/mamba/fs/filesystem.hpp
  libmamba/include/mamba/util/cast.hpp
  libmamba/include/mamba/util/compare.hpp
  libmamba/include/mamba/util/deprecation.hpp
  libmamba/include/mamba/util/encoding.hpp
  libmamba/include/mamba/util/flat_bool_expr_tree.hpp
  libmamba/include/mamba/util/flat_set.hpp
  libmamba/include/mamba/util/functional.hpp
  libmamba/include/mamba/util/string.hpp
  libmamba/src/core/download_progress_bar.cpp
  libmamba/src/core/progress_bar_impl.cpp
  libmamba/src/core/subdir_index.cpp
  libmamba/src/core/util.cpp
  libmamba/src/fs/filesystem.cpp
  libmamba/src/util/encoding.cpp
  libmamba/tests/CMakeLists.txt
  libmamba/tests/src/core/test_filesystem.cpp
  libmamba/tests/src/solver/test_problems_graph.cpp
  libmamba/tests/src/specs/test_repo_data.cpp
  libmamba/tests/src/util/test_cast.cpp
  libmamba/tests/src/util/test_compare.cpp
  libmamba/tests/src/util/test_encoding.cpp
  libmamba/tests/src/util/test_environment.cpp
  libmamba/tests/src/util/test_os_win.cpp
  libmambapy/CMakeLists.txt
  mamba_package/CMakeLists.txt
  micromamba/CMakeLists.txt
Labels: release::maintenance

#3969 Add constraint on `fmt`
  .github/workflows/static_build.yml
  dev/environment-dev.yml
  dev/environment-micromamba-static.yml
Labels: release::ci_docs

#3946 maint: Cancel activation script removal
  micromamba/etc/profile.d/mamba.sh.in
Labels: release::maintenance

#3971 Move PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: release::enhancements

#3976 Move stubs to libmambapy-stubs
  .github/workflows/unix_impl.yml
  .gitignore
  dev/compare_stubs.py
  dev/environment-dev.yml
  libmambapy-stubs/pyproject.toml
  libmambapy-stubs/setup.py
  libmambapy-stubs/src/.gitkeep
  libmambapy/src/libmambapy/__init__.pyi
  libmambapy/src/libmambapy/bindings/__init__.pyi
  libmambapy/src/libmambapy/bindings/legacy.pyi
  libmambapy/src/libmambapy/bindings/solver/__init__.pyi
  libmambapy/src/libmambapy/bindings/solver/libsolv.pyi
  libmambapy/src/libmambapy/bindings/specs.pyi
  libmambapy/src/libmambapy/bindings/utils.pyi
  libmambapy/src/libmambapy/solver/__init__.pyi
  libmambapy/src/libmambapy/solver/libsolv.pyi
  libmambapy/src/libmambapy/specs.pyi
  libmambapy/src/libmambapy/utils.pyi
  libmambapy/src/libmambapy/version.pyi
Labels: release::enhancements

#3975 Add missing init bindings from subdir structs
  libmambapy/src/libmambapy/bindings/legacy.cpp
  libmambapy/src/libmambapy/bindings/solver_libsolv.cpp
Labels: release::bug_fixes

#3968 Use range in Solution
  .github/workflows/brew.yml
  cmake/CompilerWarnings.cmake
  libmamba/include/mamba/solver/solution.hpp
  libmamba/src/core/transaction.cpp
  libmamba/src/solver/helpers.cpp
  libmamba/tests/src/solver/test_solution.cpp
  libmambapy/src/libmambapy/bindings/solver.cpp
Labels: release::maintenance

#3980 doc: Mention fix for ``libmamba Download error (7) Could not connect ...``
  docs/source/user_guide/troubleshooting.rst
Labels: release::ci_docs

#3982 Depend on LGPL builds of libarchive>=3.8
  dev/environment-dev.yml
  dev/environment-micromamba-static.yml
Labels: release::maintenance

#3974 Adapt label check to bot
  .github/workflows/label_check.yml
Labels: release::enhancements

#3887 fix: Skip inaccessible CONDA_ENVS_DIRS
  libmamba/src/api/configuration.cpp
  libmamba/src/core/fsutil.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3983 Add missing bindings
  libmambapy/src/libmambapy/bindings/legacy.cpp
Labels: release::enhancements

#3966 feat: add option revision to install command
  README.md
  libmamba/include/mamba/api/install.hpp
  libmamba/include/mamba/core/history.hpp
  libmamba/src/api/install.cpp
  micromamba/src/install.cpp
  micromamba/tests/test_install.py
Labels: release::enhancements

#3986 ci: use VS2022 instead of VS2019
  .github/workflows/tests.yml
Labels: release::ci_docs

#3991 maintenance: fixed msvc warnings about unreachable code
  libmamba/include/mamba/solver/solution.hpp
  libmamba/src/core/run.cpp
  libmamba/src/core/util_os.cpp
  libmamba/src/solver/libsolv/helpers.cpp
  libmamba/src/util/environment.cpp
  libmamba/src/util/url_manip.cpp
Labels: release::maintenance

#3998 Handle removed `is_rgb` from `fmt 11.2.0`
  libmambapy/src/libmambapy/bindings/utils.cpp
Labels: release::maintenance
