Repository mamba-org/mamba, pull requests merged in 2025-01, with the labels that each got.

#3720 fix: Adapt warnings shown when several channels are used
  libmamba/src/api/channel_loader.cpp
  libmamba/src/solver/libsolv/unsolvable.cpp
Labels: release::bug_fixes

#3715 Fix display of env activation message and co
  libmamba/include/mamba/core/transaction.hpp
  libmamba/src/api/install.cpp
  libmamba/src/core/transaction.cpp
  micromamba/tests/test_create.py
  micromamba/tests/test_env.py
  micromamba/tests/test_install.py
  micromamba/tests/test_remove.py
  micromamba/tests/test_update.py
Labels: release::bug_fixes

#3710 Fix install using explicit url
  libmamba/include/mamba/core/package_fetcher.hpp
  libmamba/src/core/package_fetcher.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3700 fix: Improve CUDA version detection
  libmamba/src/core/virtual_packages.cpp
Labels: release::bug_fixes

#3723 build: Generate and install `etc/profile.d/mamba.sh` for mamba
  mamba_package/CMakeLists.txt
  micromamba/CMakeLists.txt
  micromamba/etc/profile.d/mamba.sh.in
Labels: release::bug_fixes

#3725 fix: Honour `CONDA_ENVS_PATH` again
  libmamba/src/api/configuration.cpp
  libmamba/tests/src/core/test_configuration.cpp
Labels: release::bug_fixes

#3724 fix: Correctly populate lists of `MatchSpec` in `MTransaction`'s history
  libmamba/src/core/transaction.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3731 update_changelog.py now can also take input as cli parameters
  update_changelog.py
Labels: type::general-improvement, release::enhancements

#3722 Options args enhancement
  micromamba/src/activate.cpp
  micromamba/src/common_options.cpp
  micromamba/src/config.cpp
  micromamba/src/constructor.cpp
  micromamba/src/env.cpp
  micromamba/src/list.cpp
  micromamba/src/login.cpp
  micromamba/src/package.cpp
  micromamba/src/remove.cpp
  micromamba/src/repoquery.cpp
  micromamba/src/run.cpp
  micromamba/src/shell.cpp
  micromamba/src/update.cpp
Labels: release::enhancements

#3732 Unique Release Tag
  releaser.py
  update_changelog.py
  version_scheme.py
Labels: type::general-improvement, release::enhancements

#3721 Update Linux installation script for Nushell
  docs/source/installation/micromamba-installation.rst
Labels: release::ci_docs

#3736 fix: Add a hint on cache corruption
  libmamba/src/core/error_handling.cpp
Labels: release::bug_fixes

#3695 add more condarc paths
  libmamba/src/api/configuration.cpp
Labels: release::bug_fixes

#3738 maint: Ignore formatting changes in history
  .git-blame-ignore-revs
Labels: release::ci_docs

#3705 feat: add reverse flag to list command
  libmamba/src/api/list.cpp
  micromamba/src/list.cpp
  micromamba/tests/test_list.py
Labels: release::enhancements

#3749 maint: Correctly exclude json files in clang-format
  .pre-commit-config.yaml
  libmamba/include/mamba/util/json.hpp
Labels: release::ci_docs

#3746 maint: Update pre-commit hooks
  .pre-commit-config.yaml
  docs/source/tools/mermaid.py
  libmamba/src/core/package_database_loader.cpp
  libmamba/tests/data/repodata_json_cache/test_4.json
  libmamba/tests/src/core/test_cpp.cpp
  micromamba/tests/test_info.py
  releaser.py
Labels: release::ci_docs

#3748 maint: Don't exclude Changelog files from typos-conda
  .pre-commit-config.yaml
  CHANGELOG.md
  libmamba/CHANGELOG.md
  libmambapy/CHANGELOG.md
  micromamba/CHANGELOG.md
Labels: release::ci_docs

#3755 maint: Fix build status badge
  README.md
Labels: release::ci_docs

#3753 maint: Add missing thread and undefined sanitizers CMake options
  libmamba/CMakeLists.txt
Labels: release::bug_fixes

#3757 fix: Use `LOG_DEBUG` for CUDA version detection
  libmamba/src/core/virtual_packages.cpp
Labels: release::bug_fixes

#3743 Fix dependency and `subdir` in repoquery `whoneeds`
  libmamba/src/core/query.cpp
  micromamba/tests/helpers.py
  micromamba/tests/test_repoquery.py
Labels: release::bug_fixes

#3760 feat: add explicit flag to list command
  libmamba/src/api/list.cpp
  micromamba/src/list.cpp
  micromamba/tests/test_list.py
Labels: release::enhancements

#3764 Handle `git+https` pip urls
  libmamba/src/specs/package_info.cpp
  libmamba/tests/src/specs/test_package_info.cpp
  micromamba/tests/test-env-lock-pip-git-https.yaml
  micromamba/tests/test-env-lock.yaml
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3765 fix: Use CA certificates from `conda-forge::ca-certificates`
  libmamba/include/mamba/api/configuration.hpp
  libmamba/src/api/configuration.cpp
  libmamba/src/core/context.cpp
  libmamba/src/download/downloader.cpp
  libmamba/tests/src/download/test_downloader.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3767 Uncomment no more failing test
  micromamba/tests/test_create.py
Labels: release::ci_docs

#3768 maint: list refactoring
  libmamba/src/api/list.cpp
Labels: release::enhancements

#3745 fix: Don't encode URLs for `mamba env export --explicit`
  libmamba/tests/src/util/test_url.cpp
  micromamba/src/env.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3735 fix: Support globs in `MatchSpec` build strings
  libmamba/include/mamba/specs/regex_spec.hpp
  libmamba/src/specs/regex_spec.cpp
  libmamba/tests/src/specs/test_match_spec.cpp
  libmamba/tests/src/specs/test_regex_spec.cpp
  micromamba/tests/test_create.py
Labels: release::bug_fixes

#3773 feat: add md5 flag to list command
  libmamba/src/api/list.cpp
  micromamba/src/list.cpp
  micromamba/tests/test_create.py
  micromamba/tests/test_list.py
Labels: release::enhancements

#3770 [Windows] Fix test failure
  libmamba/src/core/prefix_data.cpp
Labels: release::ci_docs

#3782 fix: Adapt root prefix determination
  libmamba/include/mamba/core/util_os.hpp
  libmamba/src/api/configuration.cpp
  libmamba/src/core/util_os.cpp
  libmamba/src/download/downloader.cpp
  micromamba/etc/profile.d/mamba.sh.in
Labels: release::bug_fixes

#3785 maint: Factor handling of `GetModuleFileNameW`
  libmamba/src/core/util_os.cpp
Labels: release::ci_docs

#3777 feat: add canonical flag to list command
  libmamba/src/api/list.cpp
  micromamba/src/list.cpp
  micromamba/tests/test_list.py
Labels: release::enhancements
